name: API Tests

on:
  push:
    paths:
      - 'NASA.API.Tests/**'
      - '.github/workflows/api-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore NASA.API.Tests

      - name: Install SpecFlow.Plus.LivingDoc CLI
        run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI

      - name: Run tests with SpecFlow execution log
        run: >
          dotnet test NASA.API.Tests
          --filter "TestCategory!=skip"
          --logger "trx;LogFileName=test-results.trx"
          --results-directory TestResults
          -- TestRunParameters.Parameter(name=\"generateSpecFlowExecutionJson\", value=\"true\")

      - name: Generate LivingDoc HTML report
        run: livingdoc test-assembly NASA.API.Tests/bin/Debug/net8.0/NASA.API.Tests.dll -t TestResults/ > TestResults/LivingDoc.html

      - name: Upload HTML test report
        uses: actions/upload-artifact@v4
        with:
          name: api-test-report
          path: TestResults/LivingDoc.html
