name: UI Tests

on:
  push:
    paths:
      - 'NASA.UI.Tests/**'
      - '.github/workflows/ui-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore NASA.UI.Tests

      - name: Install Playwright CLI globally
        run: dotnet tool install --global Microsoft.Playwright.CLI

      - name: Add .dotnet/tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Build and install Playwright
        run: |
          dotnet build NASA.UI.Tests
          export PATH="$PATH:$HOME/.dotnet/tools"
          playwright install

      - name: Run Playwright tests with report
        run: dotnet test NASA.UI.Tests --logger "trx;LogFileName=ui-results.trx" --results-directory TestResults
        env:
          HEADLESS: true

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Generate HTML and Text Summary report
        run: reportgenerator -reports:TestResults/ui-results.trx -targetdir:TestResults/html -reporttypes:Html

      - name: Upload HTML test report
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-report
          path: TestResults/html
