name: UI Tests

on:
  push:
    paths:
      - 'NASA.UI.Tests/**'
      - '.github/workflows/ui-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore NASA.UI.Tests

      - name: Install Playwright dependencies
        run: |
          cd NASA.UI.Tests
          dotnet build
          dotnet tool restore
          playwright install
          pwsh bin/Debug/net8.0/playwright.ps1 install

      - name: Run Playwright tests with report
        run: dotnet test NASA.UI.Tests --logger "trx;LogFileName=ui-results.trx" --results-directory TestResults

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Generate HTML report
        run: reportgenerator -reports:TestResults/ui-results.trx -targetdir:TestResults/html -reporttypes:Html

      - name: Upload HTML test report
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-report
          path: TestResults/html
